steps:
- name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
  - "-c"
  - |
   docker pull gcr.io/$PROJECT_ID/scaife-viewer:${_BRANCH_NAME_ESCAPED} || exit 0
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --cache-from
  - gcr.io/$PROJECT_ID/scaife-viewer:${_BRANCH_NAME_ESCAPED}
  - --tag
  - gcr.io/$PROJECT_ID/scaife-viewer:${_BRANCH_NAME_ESCAPED}
  - --tag
  - gcr.io/$PROJECT_ID/scaife-viewer:$COMMIT_SHA
  - "."
images:
- gcr.io/$PROJECT_ID/scaife-viewer:$COMMIT_SHA
- gcr.io/$PROJECT_ID/scaife-viewer:${_BRANCH_NAME_ESCAPED}
timeout: 1200s
substitutions:
  _BRANCH_NAME_ESCAPED: '${BRANCH_NAME//\//-}'
options:
  machineType: N1_HIGHCPU_8
  dynamic_substitutions: true
