version: 2

jobs:
  qa:
    docker:
      - image: cimg/python:3.9.7-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv env
            source env/bin/activate
            pip install pip wheel --upgrade
            pip install -r requirements-dev.txt
      - run:
          name: Run isort
          command: |
            source env/bin/activate
            isort -c **/*.py
      - run:
          name: Run flake8
          command: |
            source env/bin/activate
            flake8 sv_pdl
      - run:
          name: Install static dependencies
          command: npm ci
      - run:
          name: Run eslint
          command: npm run lint
      - run:
          name: Run jest tests
          command: npm run unit
      - run:
          name: Run webpack build
          command: npm run build

  deploy:
    docker:
      - image: buildpack-deps:trusty-scm
    working_directory: ~/repo
    steps:
      - checkout
      - deploy:
          name: Heroku
          command: |
            declare -A INSTANCES=( [master]=primary )
            if [ ${INSTANCES[$CIRCLE_BRANCH]+_} ]; then
              INSTANCE="${INSTANCES[$CIRCLE_BRANCH]}"
              HEROKU_APP_NAME="scaife-perseus-org"
            else
              INSTANCE="$CIRCLE_BRANCH"
              HEROKU_APP_NAME="scaife-perseus-org-dev"
            fi
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $CIRCLE_SHA1:master
            bin/heroku/slack-notify.sh "$INSTANCE"

workflows:
  version: 2
  qa-deploy:
    jobs:
      - qa
      - deploy:
          requires:
            - qa
          filters:
            branches:
              only: /(?:master|dev)/
