name: Build base image

on:
  workflow_dispatch:

jobs:
  build-images:
    name: Build base image and push image tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker buildx build
        id: buildx
        uses: docker/setup-buildx-action@v2.5.0
        with:
          driver-opts: network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Autogenerate webapp Docker image tags
        id: autogen-docker-tags
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: ghcr.io/${{ github.repository }}/webapp-base
          # generate Docker tags based on the following events/attributes
          tags: |
            type=sha
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build base image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ./
          file: deploy/webapp/webapp-base.dockerfile
          tags: ${{ steps.autogen-docker-tags.outputs.tags }}
          push: true
